{{- if .Values.Kubernetes -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: {{ .Values.containerRuntime }}
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  systemd:
    tag: service.*
    path: /var/log/journal
    db: /fluent-bit/tail/systemd.db
    dbSync: Normal
    systemdFilter:
      {{- if .Values.fluentbit.input.systemd.systemdFilter -}}
      {{- range .Values.fluentbit.input.systemd.systemdFilter }}
      - {{ toYaml . }}
      {{- end }}
      {{- end }}
{{- end }}
